# Generated by Django 6.0.3 on 2026-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_subject_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('reading', 'Reading/Writing/Language'), ('science', 'Science')], default='math', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
