# Generated by Django 6.0.3 on 2026-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_tutor_email_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('reading', 'R/W & Language'), ('science', 'Science')], default='math', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
