# Generated by Django 6.0.3 on 2026-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='review_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
