# Generated by Django 6.0.3 on 2026-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_tutor_review_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
