# Generated by Django 6.0.7 on 2026-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
