# Generated by Django 6.0.7 on 2026-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_tutor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
